logLevel="INFO"

defaultEntryPoints = ["http", "https"]

[traefikLog]
filePath = "/etc/traefik/traefik.log"

[accessLog]
filePath = "/etc/traefik/access.log"

[entryPoints]
	[entryPoints.http]
	address = ":80"
	[entryPoints.https]
	address = ":443"
		[entryPoints.https.tls]
	[entryPoints.dashboard]
	address = ":8080"
		[entryPoints.dashboard.auth.basic]
		users = ["BASIC_AUTH"]

[api]
entrypoint = "dashboard"

[acme]
email = "EMAIL"
storage = "/etc/traefik/acme.json"
entryPoint = "https"
onHostRule = true
	[acme.httpChallenge]
	entryPoint = "http"

[docker]
domain = "DOMAIN"
watch = true
exposedByDefault = false