version: "3.7"

services:
  gitea:
    image: gitea/gitea:latest
    environment:
      - USER_UID=${UID}
      - USER_GID=${GID}
      - DB_TYPE=${DB_TYPE}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWD=${DB_PASSWD}
    restart: unless-stopped
    volumes:
      - gitea:/data
      - /home/git/.ssh:/data/git/.ssh
    ports:
      - "127.0.0.1:2222:22"
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.redirect.entryPoint=https"
      - "traefik.frontend.rule=Host:${DOMAIN}"
      - "traefik.port=3000"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
    networks:
      - traefik
  gitea_db:
    image: demyx/mariadb
    restart: unless-stopped
    volumes:
      - gitea_db:/var/lib/mysql
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USERNAME: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    networks:
      - traefik
volumes:
  gitea:
    name: gitea
  gitea_db:
    name: gitea_db
networks:
  traefik:
    name: traefik
